djangoProject/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from movies import views



urlpatterns = [
    path('', views.MovieListView.as_view(), name='movie-list'),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls'))
]

djangoProject/movies/urls.py
from django.urls import path
from . import views
from .views import SeriesDetailView, SearchView

app_name = 'movies'

urlpatterns = [
    path('', views.MovieListView.as_view(), name='movie-list'),
    path('movies/<int:pk>/', views.MovieDetailView.as_view(), name='movie-detail'),
    path('movies/<slug:slug>/', views.MovieDetailView.as_view(), name='movie-detail'),


    path('series/', views.SeriesListView.as_view(), name='series-list'),
    path('series/<int:pk>/', views.SeriesDetailView.as_view(), name='series-detail'),
    path('series/<slug:slug>/', SeriesDetailView.as_view(), name='series-detail'),

    # ... Search URL patterns ...
    path('search/', SearchView.as_view(), name='search-results'),

    path('genres/<int:pk>/', views.GenreMoviesSeriesView.as_view(), name='genre-movies-series'),
    path('genres/', views.GenreListView.as_view(), name='genre-list'),
    path('genres/<int:pk>/', views.GenreMoviesSeriesView.as_view(), name='genre_movies_series'),
    # Other URL patterns
]

djangoProject/movies/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify



# Genre.
class Genre(models.Model):
     name = models.CharField(max_length=100)
     slug = models.SlugField(unique=True,default='')

     def save(self, *args, **kwargs):
         if not self.slug:
             self.slug = slugify(self.name)
         super().save(*args, **kwargs)

     def __str__(self):
         return self.name


class Movie(models.Model):
     title = models.CharField(max_length=200)
     description = models.TextField(blank=True, null=True)
     release_date = models.DateField(blank=True, null=True)
     is_featured = models.BooleanField(default=False)
     genres = models.ManyToManyField(Genre)
     thumbnail_url = models.URLField(blank=True, null=True)
     trailer_url = models.URLField(blank=True, null=True)
     video_url = models.URLField(blank=True, null=True)
     slug = models.SlugField(unique=True, blank=True)

     def save(self, *args, **kwargs):
         if not self.slug:
             self.slug = slugify(self.title)
         super().save(*args, **kwargs)

     def __str__(self):
         return self.title


# Series model
class Series(models.Model):
     title = models.CharField(max_length=200)
     description = models.TextField(blank=True, null=True)
     release_date = models.DateField(blank=True, null=True)
     is_featured = models.BooleanField(default=False)
     genres = models.ManyToManyField(Genre)
     thumbnail_url = models.URLField(blank=True, null=True)
     trailer_url = models.URLField(blank=True, null=True)
     slug = models.SlugField(unique=True) # Add slug field for URLs

     def __str__(self):
         return self.title

     def get_absolute_url(self):
         return reverse('series-detail', args=[str(self.slug)])


class Season(models.Model):
     series = models.ForeignKey(Series, on_delete=models.CASCADE)
     title = models.CharField(max_length=100)
     release_date = models.DateField(blank=True, null=True)
     thumbnail_url = models.URLField(blank=True, null=True)

     def __str__(self):
         return f"{self.series.title} - {self.title}"


class Episode(models.Model):
     season = models.ForeignKey(Season, on_delete=models.CASCADE)
     title = models.CharField(max_length=100)
     release_date = models.DateField(blank=True, null=True)
     video_url = models.URLField(blank=True, null=True)

     def __str__(self):
         return f"{self.season.series.title} - {self.season.title} - {self.title}"

djangoProject/movies/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=100)

djangoProject/movies/views.py
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import ListView, DetailView
from .models import Movie, Series, Genre
from itertools import zip_longest


class MovieListView(ListView):
    model = Movie
    template_name = 'movies/movie_list.html'  # Create this template
    context_object_name = 'movie_list'
    queryset = Movie.objects.order_by('-release_date')  # Order movies by release date descending
    paginate_by = 9


class MovieDetailView(DetailView):
    model = Movie
    template_name = 'movies/movie_detail.html'
    context_object_name = 'movie'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        movie = self.get_object()  # Get the current movie instance
        featured_movies = Movie.objects.filter(is_featured=True).exclude(id=movie.id)[:9]
        chunks = [featured_movies[i:i+3] for i in range(0, len(featured_movies), 3)]
        context['carousel_chunks'] = chunks
        return context

class SeriesListView(ListView):
    model = Series
    template_name = 'movies/series_list.html'  # Path to your template
    context_object_name = 'series_list'
    queryset = Series.objects.order_by('-release_date')  # Order movies by release date descending
    paginate_by = 9


class SeriesDetailView(DetailView):
    model = Series
    template_name = 'movies/series_detail.html'  # Path to your template
    context_object_name = 'series'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        related_series = Series.objects.exclude(slug=self.kwargs['slug'])

        chunk_size = 3
        related_series_chunks = [related_series[i:i + chunk_size] for i in range(0, len(related_series), chunk_size)]

        context['related_series_chunks'] = related_series_chunks
        return context


# SearchView
class SearchView(View):
    template_name = 'movies/search_results.html'

    def get(self, request, *args, **kwargs):
        query = request.GET.get('query')
        movies = Movie.objects.filter(title__icontains=query)
        series = Series.objects.filter(title__icontains=query)
        context = {'query': query, 'movies': movies, 'series': series}
        return render(request, self.template_name, context)



class GenreListView(ListView):
    model = Genre
    template_name = 'movies/genre_list.html'
    context_object_name = 'genres'


class GenreDetailView(DetailView):
    model = Genre
    template_name = 'movies/genre_detail.html'
    context_object_name = 'genre'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        genre = self.object
        context['movies'] = genre.movie_set.all()
        context['series'] = genre.series_set.all()
        return context


class GenreMoviesSeriesView(View):
    template_name = 'movies/genre_movies_series.html'

    def get(self, request, pk):
        genre = get_object_or_404(Genre, pk=pk)
        movies = Movie.objects.filter(genres=genre)
        series = Series.objects.filter(genres=genre)

        context = {
            'genre': genre,
            'movies': movies,
            'series': series,
        }
        return render(request, self.template_name, context)

djangoProject/movies/templates/movies/footer.html
<!-- Footer -->
<nav class="navbar navbar-expand-lg text-light justify-content-center navbar-dark bg-dark mt-5">
  <div class="container-fluid">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">© {{ current_year }} Your Website Name. All rights reserved.</li>
      </ul>
      <span class="navbar-text">
          <!-- Go to Top Button -->
        <a id="goToTopBtn" class="btn btn-outline-primary float-end" style="display:none;">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-bar-up" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 10a.5.5 0 0 0 .5-.5V3.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 3.707V9.5a.5.5 0 0 0 .5.5zm-7 2.5a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13a.5.5 0 0 1-.5-.5z"/>
            </svg>
        </a>
      </span>
    </div>
</nav>

djangoProject/movies/templates/movies/genre_list.html
{% for genre in genres %}
    <ul class="list-group">
        <li class="list-group-item">
            <a href="{% url 'genre-detail' genre.pk %}">{{ genre.name }}</a>
        </li>
    </ul>

{% endfor %}

djangoProject/movies/templates/movies/genre_list_dropdown.html
<!-- genre_list_dropdown.html -->

    <ul class="dropdown-menu" aria-labelledby="genreDropdown">
        {% for genre in genres %}
            <li><a class="dropdown-item" href="{% url 'movies:genre-movies-series' genre.pk %}">{{ genre.name }}</a></li>
        {% endfor %}
    </ul>

djangoProject/movies/templates/movies/genre_movies_series.html
{% extends "base.html" %}

{% block content %}
    <div class="container mt-4">
        <h1>{{ genre.name }} Movies and Series</h1>

        <h2>Movies</h2>
        <div class="row">
            {% for movie in movies %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img src="{{ movie.thumbnail_url }}" class="card-img-top" alt="{{ movie.title }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ movie.title }}</h5>
                            <p class="card-text">{{ movie.release_date }}</p>
                            <a href="{{ movie.video_url }}" class="btn btn-primary">Watch Now</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <h2>Series</h2>
        <div class="row">
            {% for serie in series %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img src="{{ serie.thumbnail.url }}" class="card-img-top" alt="{{ serie.title }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ serie.title }}</h5>
                            <p class="card-text">{{ serie.release_date }}</p>
                            <a href="{{ serie.trailer_url }}" class="btn btn-primary">Watch Trailer</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

djangoProject/movies/templates/movies/movie_list.html
{% extends "base.html" %}

{% block content %}
    <!-- Carousel -->
    <div class="container">
        <div id="featuredCarousel" class="carousel slide mb-4" data-bs-ride="carousel">
            <div class="carousel-inner">
                {% for movie in movie_list %}
                    <div class="carousel-item {% if forloop.first %}active{% endif %}">
                    <a href="{% url 'movies:movie-detail' slug=movie.slug %}">
                        <img src="{{ movie.thumbnail_url }}" class="d-block w-100" alt="{{ movie.title }}">
                    </a>
                        <!-- <div class="carousel-caption">
                            <h3>{{ movie.title }}</h3>
                            <p>{{ movie.description }}</p>
                        </div>-->
                    </div>
                {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#featuredCarousel" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#featuredCarousel" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>

    <div class="container">
        <div class="row">
            {% for movie in movie_list %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <a href="{% url 'movies:movie-detail' slug=movie.slug %}">
                            <img src="{{ movie.thumbnail_url }}" class="card-img-top" height="150" alt="{{ movie.title }} Thumbnail">
                        </a>
                        <div class="card-body">
                            <h5 class="card-title">{{ movie.title|truncatechars:20 }}</h5>
                            <p class="card-text badge bg-primary text-wrap">
                                <strong>Release Date:</strong> {{ movie.release_date }}
                            </p>
                            <a type="button" href="{% url 'movies:movie-detail' slug=movie.slug %}" class="btn btn-outline-primary btn-sm me-3">Watch Movie</a>
                            <a type="button" class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#thrillerModal{{ movie.id }}">Watch Trailer</a>
                        </div>
                    </div>
                </div>

                <!-- Trailer Modal -->
                <div class="modal modal-lg fade bg-dark" id="thrillerModal{{ movie.id }}" tabindex="-1" aria-labelledby="thrillerModalLabel{{ movie.id }}" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="thrillerModalLabel{{ movie.id }}">Trailer for {{ movie.title }}</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <div class="embed-responsive embed-responsive-16by9">
                                    <iframe class="embed-responsive-item" width="100%" height="450" src="{{ movie.trailer_url }}"></iframe>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    {% include 'movies/paginator.html' %}
{% endblock %}

djangoProject/movies/templates/movies/movies_by_genre.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ genre.name }} Movies and Series</h1>

    <h2>Movies</h2>
    <div class="row">
        {% for movie in movies %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{{ movie.thumbnail_url }}" class="card-img-top" alt="{{ movie.title }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ movie.title }}</h5>
                        <p class="card-text">{{ movie.release_date }}</p>
                        <!-- Add more movie details here -->
                        <a href="{{ movie.video_url }}" class="btn btn-primary">Watch Now</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <h2>Series</h2>
    <div class="row">
        {% for serie in series %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    <img src="{{ serie.thumbnail.url }}" class="card-img-top" alt="{{ serie.title }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ serie.title }}</h5>
                        <p class="card-text">{{ serie.release_date }}</p>
                        <!-- Add more series details here -->
                        <a href="{{ serie.trailer_url }}" class="btn btn-primary">Watch Trailer</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

djangoProject/movies/templates/movies/multi_carousel.html
<!-- Multi-Item Carousel -->

<div class="carousel-buttons text-end mb-1">
    <button class="btn btn-outline-primary carousel-button-prev" data-bs-target="#multiCarousel" data-bs-slide="prev">
        <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 320 512">
            <!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
            <path d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l192 192c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L77.3 256 246.6 86.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-192 192z"/>
        </svg>
    </button>
    <button class="btn btn-outline-primary carousel-button-next" data-bs-target="#multiCarousel" data-bs-slide="next">
        <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 320 512">
            <!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
            <path d="M310.6 233.4c12.5 12.5 12.5 32.8 0 45.3l-192 192c-12.5 12.5-32.8 12.5-45.3 0s-12.5-32.8 0-45.3L242.7 256 73.4 86.6c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0l192 192z"/>
        </svg>
    </button>
</div>

<div id="multiCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        {% for chunk in carousel_chunks %}
        <div class="carousel-item {% if forloop.first %}active{% endif %}">
            <div class="d-flex justify-content-between">
                {% for movie in chunk %}
                <div class="card mb-4">
                    <a href="{% url 'movies:movie-detail' slug=movie.slug %}">
                        <img src="{{ movie.thumbnail_url }}" class="card-img-top" alt="{{ movie.title }} Thumbnail">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
   <!-- <button class="carousel-control-prev" type="button" data-bs-target="#multiCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#multiCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button> -->
</div>

djangoProject/movies/templates/movies/search_results.html
{% extends 'base.html' %}

{% block title %}Search Results{% endblock %}

{% block content %}
    <h1>Search Results</h1>
    <p>Showing results for: <strong>{{ query }}</strong></p>
    <hr class="bg-dark">

    <div class="row">
        {% for movie in movies %}
            <div class="col-md-4 mb-2">
                <div class="card">
                    <a href="{% url 'movies:movie-detail' movie.pk %}">
                        <img src="{{ movie.thumbnail_url }}" width="250" height="150" class="card-img-top" alt="{{ movie.title }}">
                    </a>
                </div>
            </div>
            {% empty %}
            <p class="list-group-item">No movies results found.</p>
        {% endfor %}

        {% for serie in series %}
            <div class="col-md-4 mb-2">
                <div class="card">
                    <a href="{% url 'movies:series-detail' serie.slug %}">
                        <img src="{{ serie.thumbnail_url }}" width="250"  height="150" class="card-img-top" alt="{{ serie.title }}">
                    </a>
                </div>
            </div>
            {% empty %}
            <p class="list-group-item">No series results found.</p>
        {% endfor %}
    </div>
{% endblock %}

djangoProject/movies/templates/movies/series_carousel.html
<!-- Multi series-Item Carousel -->

<div class="carousel-buttons text-end mb-1">
    <button class="btn btn-outline-primary carousel-button-prev" data-bs-target="#seriesCarousel" data-bs-slide="prev">
        <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 320 512">
            <!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
            <path d="M9.4 233.4c-12.5 12.5-12.5 32.8 0 45.3l192 192c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L77.3 256 246.6 86.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-192 192z"/>
        </svg>
    </button>
    <button class="btn btn-outline-primary carousel-button-next" data-bs-target="#seriesCarousel" data-bs-slide="next">
        <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 320 512">
            <!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
            <path d="M310.6 233.4c12.5 12.5 12.5 32.8 0 45.3l-192 192c-12.5 12.5-32.8 12.5-45.3 0s-12.5-32.8 0-45.3L242.7 256 73.4 86.6c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0l192 192z"/>
        </svg>
    </button>
</div>

<div id="seriesCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        {% for chunk in related_series_chunks %}
        <div class="carousel-item {% if forloop.first %}active{% endif %}">
            <div class="d-flex justify-content-between">
                {% for series in chunk %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <a href="{% url 'movies:series-detail' slug=series.slug %}">
                            <img src="{{ series.thumbnail_url }}" class="card-img-top" alt="{{ series.title }}">
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>

  <!--  <button class="carousel-control-prev" type="button" data-bs-target="#seriesCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#seriesCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button> -->
</div>

djangoProject/movies/templates/movies/series_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-4 mt-4">
            <!-- Series Card -->
            <div class="card">
                <img src="{{ series.thumbnail_url }}" class="card-img-top" alt="{{ series.title }} Thumbnail">
                <div class="card-body">
                    <h5 class="card-title">{{ series.title }}</h5>
                    <p class="card-text badge bg-primary text-wrap">
                        <strong>Release Date:</strong> {{ series.release_date }}
                    </p>
                    <!-- Read more and Less -->
                    <div class="movie-description">
                        <p class="description-text">{{ series.description|truncatechars:150 }}</p>
                        <button class="btn btn-outline-primary read-more-button">Read More</button>
                    </div>
                </div>
            </div>
        </div>

    <div class="col-sm-8 mt-4">
    <!-- Seasons Accordion -->
        <div class="accordion accordion-flush" id="accordionFlushExample">
            {% for season in series.season_set.all %}
                <div class="accordion-item">
                    <h2 class="accordion-header" id="flush-heading{{ season.id }}">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#flush-collapse{{ season.id }}" aria-expanded="false"
                                aria-controls="flush-collapse{{ season.id }}">
                            Season {{ season.title }}
                        </button>
                    </h2>
                    <div id="flush-collapse{{ season.id }}" class="accordion-collapse collapse"
                         aria-labelledby="flush-heading{{ season.id }}" data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body">
                            <!-- Episodes Accordion -->
                            <div class="accordion" id="episodesAccordion{{ season.id }}">
                                {% for episode in season.episode_set.all %}
                                    <div class="accordion-item">
                                        <h2 class="accordion-header" id="episode{{ episode.id }}Heading">
                                            <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                                    data-bs-target="#episode{{ episode.id }}Collapse" aria-expanded="true"
                                                    aria-controls="episode{{ episode.id }}Collapse">
                                                Episode {{ episode.title }}
                                            </button>
                                        </h2>
                                        <div id="episode{{ episode.id }}Collapse" class="accordion-collapse collapse"
                                             aria-labelledby="episode{{ episode.id }}Heading"
                                             data-bs-parent="#episodesAccordion{{ season.id }}">
                                            <div class="accordion-body">
                                                <!-- Bootstrap iframe for video -->
                                                <div class="embed-responsive embed-responsive-16by9">
                                                    <iframe class="embed-responsive-item" width="100%" height="300" src="{{ episode.video_url }}"></iframe>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    </div>
</div>
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-12">
                <h5 class="card-title">Featured Series</h5>
                <hr>
                {% include 'movies/series_carousel.html' with series_list=related_series %}
            </div>
        </div>
    </div>

    <script>
        const readMoreButton = document.querySelector('.read-more-button');
        const descriptionText = document.querySelector('.description-text');
        const originalDescription = '{{ series.description }}';
        const truncatedDescription = '{{ series.description|truncatechars:150 }}';

        readMoreButton.addEventListener('click', () => {
            if (readMoreButton.textContent === 'Read More') {
                descriptionText.textContent = originalDescription;
                readMoreButton.textContent = 'Read Less';
                descriptionText.style.maxHeight = 'none'; /* Expand to full height */
            } else {
                descriptionText.textContent = truncatedDescription;
                readMoreButton.textContent = 'Read More';
                descriptionText.style.maxHeight = '150px'; /* Collapse to initial height */
            }
        });
    </script>

{% endblock %}

djangoProject/movies/templates/movies/series_list.html
<!-- series_list.html -->

{% extends "base.html" %}

{% block content %}
    <!-- Carousel -->
    <div class="container">
        <div id="featuredCarousel" class="carousel slide mb-4" data-bs-ride="carousel">
            <div class="carousel-inner">
                {% for series in series_list %}
                    <div class="carousel-item {% if forloop.first %}active{% endif %}">
                    <a href="{% url 'movies:series-detail' slug=series.slug %}">
                        <img src="{{ series.thumbnail_url }}" class="d-block w-100" alt="{{ series.title }}">
                    </a>
                        <!--<div class="carousel-caption">
                            <h3>{{ series.title }}</h3>
                            <p>{{ series.description }}</p>
                        </div>-->
                    </div>
                {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#featuredCarousel" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#featuredCarousel" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    </div>

    <!-- List Series  -->
    <div class="container">
        <div class="row">
            {% for series in series_list %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <a href="{% url 'movies:series-detail' slug=series.slug %}">
                            <img src="{{ series.thumbnail_url }}" class="card-img-top" height="150" alt="{{ series.title }} Thumbnail">
                        </a>
                            <div class="card-body">
                            <h5 class="card-title">{{ series.title|truncatechars:20 }}</h5>
                            <p class="card-text badge bg-primary text-wrap">
                                <strong>Release Date:</strong> {{ series.release_date }}
                            </p>
                            <a href="{% url 'movies:series-detail' slug=series.slug %}" class="btn btn-outline-primary btn-sm me-3">
                                Watch Series
                            </a>
                            <a type="button" class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#thrillerModal{{ series.id }}">
                                Watch Trailer
                            </a>
                        </div>
                    </div>
                </div>

                <!-- Trailer Modal -->
                <div class="modal modal-lg fade bg-dark" id="thrillerModal{{ series.id }}" tabindex="-1" aria-labelledby="thrillerModalLabel{{ series.id }}" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="thrillerModalLabel{{ series.id }}">Trailer for {{ series.title }}</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <div class="embed-responsive embed-responsive-16by9">
                                    <iframe class="embed-responsive-item" width="100%" height="450" src="{{ series.trailer_url }}"></iframe>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        {% endfor %}
    </div>
</div>

    {% include 'movies/paginator.html' %}
{% endblock %}